# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Collect Info
        run: |
          commit=release-`git log -1 --format='%h'`
          title=`git log -1 --format='%f'`
          echo commit=$commit >> $GITHUB_ENV
          echo title=$title >> $GITHUB_ENV

          if [[ $title =~ "release" ]]; then echo pre=false >> $GITHUB_ENV; elif [[ $title =~ "pre-release" ]]; then echo pre=true >> $GITHUB_ENV;
          else echo "::notice Not_Release";echo exit=true >> $GITHUB_ENV; echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`";fi

          echo Auto Generated Release > commit.tmp.txt
          echo >> commit.tmp.txt
          git log -1 >> commit.tmp.txt
      - name: Check Is Release
        uses: andymckay/cancel-action@0.2
        if: ${{ env.exit }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.commit }}
          name: ${{ env.title }}
          body_path: commit.tmp.txt
          prerelease: ${{ env.pre }}
